/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DraftFvciEkycBenificialOwnerDetailsDto { 
    id?: string;
    fvciApplicationId?: string;
    nameAddress?: string;
    dateOfBirth?: Date;
    taxResidancyJuridication?: string;
    nationality?: string;
    actingAlongPersonGroupNameAddress?: string;
    boOwnershipInFvci?: number;
    govermentDocIdentityNumber?: string;
    status?: number;
    createdAt?: Date;
    updatedAt?: Date;
}