FROM node:20-slim AS builder

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular application in production mode
RUN npm run build

#stage 2 for nginx
FROM nginx:alpine
COPY --from=builder /app/dist/nsdl-fpi/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

# Start the server with the correct path to the production build
# CMD ["npx", "http-server", "/app/dist/nsdl-fpi-revamp/browser/", "-p", "80", "-o", "--proxy", "http://127.0.0.1:80?"]



