/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CertificateUpdateRequest { 
    application_id?: number;
    asm_id?: number;
    cert_serial_no?: string;
    cert_thumbprint?: string;
    cert_validdate?: string;
    cert_subname?: string;
}