/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DraftFvciTelephoneNumberDetailsDto { 
    id?: number;
    fvciApplicationId?: string;
    countryCode?: string;
    stdCode?: string;
    phoneNumber?: string;
    phoneType?: string;
    status?: number;
    contactType?: string;
    createdAt?: Date;
    updatedAt?: Date;
}