/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DraftFvicKycDetailsDto { 
    id?: number;
    fvciApplicationId?: string;
    name?: string;
    hasOtherName?: boolean;
    otherName?: string;
    dateOfIncorporation?: Date;
    dateOfCommencement?: Date;
    placeOfIncorporation?: string;
    countryOfIncorporation?: string;
    isdCountryCodeOfIncorporation?: string;
    legalFormAndLawOfIncorporation?: string;
    legalEntityIdentifier?: string;
    addressOfCommunication?: string;
    haveOfficeInIndia?: boolean;
    benificialOwnershipHolding?: number;
    doesOtherPersonHolderOwnership?: boolean;
    isPoliticallyExposed?: boolean;
    isRelatedToPoliticallyExposed?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}