/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DraftFvciDeclarationUndertakingDetailsDto { 
    id?: number;
    fvciApplicationId?: string;
    name?: string;
    capacity?: string;
    date?: Date;
    place?: string;
    nameOfSignatory?: string;
    designationOfSignatory?: string;
    dateOfSignature?: Date;
    signature?: string;
    createdAt?: Date;
    updatedAt?: Date;
}