/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DraftFvciInfoBasicOfOwnershipBoDetailsDto { 
    id?: number;
    fvciApplicationId?: string;
    nameOfBo?: string;
    stake?: number;
    nameOfEntity?: string;
    country?: string;
    stakePercentage?: number;
    isIndividual?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}