/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserAsType } from './userAsType';

export interface UserRegistrationDto { 
    user_as: UserAsType;
    role_id?: number;
    user_type_id?: number;
    dob?: Date;
    user_name_fpi_app?: string;
    entity_name?: string;
    specify_reg?: string;
    specify_other?: string;
    lei_reg_no?: string;
    lei_details?: string;
    gc_name?: string;
    gc_reg_no?: string;
    gc_name_of_user?: string;
    city: string;
    state: string;
    pincode: string;
    country: string;
    country_code: string;
    address_1?: string;
    address_2?: string;
    address_3?: string;
    number: string;
    area_code: string;
    email_id: string;
    password: string;
}