/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DraftFvciAddressDetailsDto } from './draftFvciAddressDetailsDto';
import { DraftFvciBenificialOwnershipByControlBoDetailsDto } from './draftFvciBenificialOwnershipByControlBoDetailsDto';
import { DraftFvciBenificialOwnershipByControlDto } from './draftFvciBenificialOwnershipByControlDto';
import { DraftFvciComplianceOfficerDetailsDto } from './draftFvciComplianceOfficerDetailsDto';
import { DraftFvciComplianceOfficerEmailDto } from './draftFvciComplianceOfficerEmailDto';
import { DraftFvciDeclarationUndertakingDetailsDto } from './draftFvciDeclarationUndertakingDetailsDto';
import { DraftFvciEkycBenificialOwnerDetailsDto } from './draftFvciEkycBenificialOwnerDetailsDto';
import { DraftFvciEkycContactDetailsDto } from './draftFvciEkycContactDetailsDto';
import { DraftFvciFaxNumberDetailsDto } from './draftFvciFaxNumberDetailsDto';
import { DraftFvciGlobalCustodianDetailsDto } from './draftFvciGlobalCustodianDetailsDto';
import { DraftFvciIncidentsOfLawViolationDto } from './draftFvciIncidentsOfLawViolationDto';
import { DraftFvciIncomeDetailsDto } from './draftFvciIncomeDetailsDto';
import { DraftFvciIndianMarketAssociansDto } from './draftFvciIndianMarketAssociansDto';
import { DraftFvciInfoBasicOfOwnershipBoDetailsDto } from './draftFvciInfoBasicOfOwnershipBoDetailsDto';
import { DraftFvciInformationOfSaSmFvciApplicantDto } from './draftFvciInformationOfSaSmFvciApplicantDto';
import { DraftFvciInvestmentManagerDetailsDto } from './draftFvciInvestmentManagerDetailsDto';
import { DraftFvciIsBankDto } from './draftFvciIsBankDto';
import { DraftFvciKraPermissionDto } from './draftFvciKraPermissionDto';
import { DraftFvciKycDocumentDto } from './draftFvciKycDocumentDto';
import { DraftFvciKycLeiDetailsDto } from './draftFvciKycLeiDetailsDto';
import { DraftFvciOwnershipDetailsDto } from './draftFvciOwnershipDetailsDto';
import { DraftFvciRegulatoryAuthorityDetailsDto } from './draftFvciRegulatoryAuthorityDetailsDto';
import { DraftFvciSubClassDetailsDto } from './draftFvciSubClassDetailsDto';
import { DraftFvciTelephoneNumberDetailsDto } from './draftFvciTelephoneNumberDetailsDto';
import { DraftFvicKycDetailsDto } from './draftFvicKycDetailsDto';
import { DraftFvicRegistrationDetailsDto } from './draftFvicRegistrationDetailsDto';

export interface DraftFvciApplicationDto { 
    id?: number;
    userId?: number;
    applicationId?: string;
    fvciRegistrationNumber?: string;
    createdAt?: Date;
    updatedAt?: Date;
    status?: number;
    kycDetails?: DraftFvicKycDetailsDto;
    kycLeiDetails?: Array<DraftFvciKycLeiDetailsDto>;
    addressDetails?: Array<DraftFvciAddressDetailsDto>;
    telephoneNumberDetails?: Array<DraftFvciTelephoneNumberDetailsDto>;
    faxNumberDetails?: Array<DraftFvciFaxNumberDetailsDto>;
    contactDetails?: DraftFvciEkycContactDetailsDto;
    investmentManagerDetails?: DraftFvciInvestmentManagerDetailsDto;
    complianceOfficerDetails?: DraftFvciComplianceOfficerDetailsDto;
    complianceOfficerEmail?: DraftFvciComplianceOfficerEmailDto;
    kycDocuments?: Array<DraftFvciKycDocumentDto>;
    regulatoryAuthorityDetails?: DraftFvciRegulatoryAuthorityDetailsDto;
    globalCustodianDetails?: DraftFvciGlobalCustodianDetailsDto;
    declarationUndertakingDetails?: DraftFvciDeclarationUndertakingDetailsDto;
    isBank?: DraftFvciIsBankDto;
    kraPermission?: DraftFvciKraPermissionDto;
    ownershipDetails?: DraftFvciOwnershipDetailsDto;
    ekycBenificialOwnerDetails?: Array<DraftFvciEkycBenificialOwnerDetailsDto>;
    incomeDetails?: DraftFvciIncomeDetailsDto;
    registrationDetails?: DraftFvicRegistrationDetailsDto;
    benificialOwnershipByControlBoDetails?: Array<DraftFvciBenificialOwnershipByControlBoDetailsDto>;
    benificialOwnershipByControl?: DraftFvciBenificialOwnershipByControlDto;
    infoBasicOfOwnershipBoDetails?: Array<DraftFvciInfoBasicOfOwnershipBoDetailsDto>;
    informationOfSaSmFvciApplicant?: Array<DraftFvciInformationOfSaSmFvciApplicantDto>;
    subClassDetails?: Array<DraftFvciSubClassDetailsDto>;
    incidentsOfLawViolation?: DraftFvciIncidentsOfLawViolationDto;
    indianMarketAssocians?: Array<DraftFvciIndianMarketAssociansDto>;
}