/**
 * NSDL API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DraftFvciSubClassBenificialOwnerDetailsDto { 
    id?: number;
    fvciSubClassDetailsId?: number;
    name?: string;
    relationshipWithApplicant?: string;
    pan?: string;
    nationality?: string;
    dateOfBirth?: Date;
    residentialAddress?: string;
    governmentDocIdentityNumber?: string;
    status?: number;
    createdAt?: Date;
    updatedAt?: Date;
}