ALTER TABLE nsdlcaf.dbo.draft_DeclarationAndUndertakingForm ALTER COLUMN [Date] datetime NULL;
ALTER TABLE nsdlcaf.dbo.draft_DeclarationAndUndertakingForm ALTER COLUMN Place nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE nsdlcaf.dbo.draft_DeclarationAndUndertakingForm ALTER COLUMN Capacity nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE nsdlcaf.dbo.draft_DeclarationAndUndertakingForm ALTER COLUMN NameOfSignatory nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE nsdlcaf.dbo.draft_DeclarationAndUndertakingForm ALTER COLUMN DesignationOfSignatory nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE nsdlcaf.dbo.DeclarationAndUndertakingForm ALTER COLUMN [Date] datetime NULL;
ALTER TABLE nsdlcaf.dbo.DeclarationAndUndertakingForm ALTER COLUMN Place nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE nsdlcaf.dbo.DeclarationAndUndertakingForm ALTER COLUMN Capacity nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE nsdlcaf.dbo.DeclarationAndUndertakingForm ALTER COLUMN NameOfSignatory nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;
ALTER TABLE nsdlcaf.dbo.DeclarationAndUndertakingForm ALTER COLUMN DesignationOfSignatory nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL;